use crate::circuit::structure::constant_wire;
use crate::circuit::structure::wire_type::WireType;

/**
 * Pk derivation part of jsnark's ECDHKeyExchangeGadget
 */

pub struct ZkayEcPkDerivationGadget {
    // The Affine point representation is used as it saves one gate per bit
    basePoint: AffinePoint, // The Base point both parties agree to

    secretBits: Vec<Option<WireType>>, // the bits of the secret generated by this party
    // (follows little-endian order)

    // gadget output
    outputPublicValue: &Option<WireType>, // the x-coordinate of the key exchange
                                          // material to be sent to the other party
                                          // outputPublicValue = ((this party's
                                          // secret)*Base).x
}

impl ZkayEcPkDerivationGadget {
    pub fn new(
        secretKey: &WireType,
        validateSecret: bool,
        desc: &Option<String>,
        generator: RcCell<CircuitGenerator>,
    ) -> Gadget<ZkayEcGadget<Self>> {
        let mut _self = ZkayEcGadget::<Self>::new(
            desc,
            Self {
                secretBits: secretKey.getBitWires(SECRET_BITWIDTH).asArray(),
                basePoint: AffinePoint::new(generator.createConstantWire(4)),
                outputPublicValue: None,
            },
            generator,
        );
        // Hardcode base point
        if validateSecret {
            _self.checkSecretBits(generator, secretBits);
        }
        _self.computeYCoordinates(); // For efficiency reasons, we rely on affine
        // coordinates
        _self.buildCircuit();
        _self
    }
}
impl Gadget<ZkayEcGadget<ZkayEcPkDerivationGadget>> {
    fn buildCircuit(&mut self) {
        let baseTable = self.preprocess(&self.t.t.basePoint);
        let outputPublicValue = self
            .mul(&self.t.t.basePoint, &self.t.t.secretBits, baseTable)
            .x;
        self.t.t.outputs = vec![outputPublicValue.clone()];
        self.t.t.outputPublicValue = Some(outputPublicValue);
    }

    fn computeYCoordinates(&self) {
        let x = (basePoint.x).getConstant();
        basePoint.y = generator.createConstantWire(computeYCoordinate(x));
    }
}
impl GadgetConfig for Gadget<ZkayEcGadget<ZkayEcPkDerivationGadget>> {
    fn getOutputWires(&self) -> &Vec<Option<WireType>> {
        &self.t.t.outputs
    }
}
